### ISSUE TITLE
Add Search

### ISSUE THREAD

**Issue by stacyk** [oddbird/sassdoc-theme-herman#28] opened 2016-09-10 15:15 UTC
Perhaps we should add a search for easier ways to find things.

(This is for the entire styleguide, while #52 helps filtering a single page)

**Comment by mirisuzanne** [comment] 2017-05-19 18:35
Duplicate of the better-documented #52

**Comment by jgerigmeyer** [comment] 2017-11-20 17:42
@mirisuzanne @stacyk @SondraE It'd be helpful to have a basic design mockup for this feature. Where does the search bar live -- on every page? on a dedicated Search page? Where are results displayed?

**Comment by stacyk** [comment] 2017-11-20 21:46
@jgerigmeyer I was thinking it could be either top right or in nav on left. then it is on every page, but results would be shown where the main content normally is on its own dedicated results page. 
![search-mock](https://user-images.githubusercontent.com/1581694/33043142-f34794c4-ce09-11e7-94d4-ec1744cde39b.jpg)

**Comment by mirisuzanne** [comment] 2017-11-20 23:28
Nav bar location will work at all page sizes. Let's start there? Then we can add to the top-bar on large screens if we want.

**Comment by jgerigmeyer** [comment] 2017-11-29 21:06
Fixed by #203.

**Closed by jgerigmeyer** 2017-11-29 21:06 UTC
Labels: enhancement, promote?, ready for review
