### ISSUE TITLE
Cannot make Herman Theme to work

### ISSUE THREAD

**Issue by TheoKondak** [oddbird/sassdoc-theme-herman#371] opened 2022-04-21 21:02 UTC
Hello and thank you for your amazing work!

For the past couple of days I've been trying to use the Herman theme, but I keep stumbling upon errors.

I am trying to document a sass library I am working on. This library is an npm package and I usually use it as such.

The library has `@mixin`s , `@function`s, as well as some `$variables`.  All the files are inside a `sin-core` folder.

I am using the library by installing it through npm and then importing it to my projects through a `_sin.scss` file. 
`@forward '../node_modules/@get-sinister/sass/sin-core';`

Now I am trying to document the `sin-core` folder but i keep stumbling upon errors. (see at the bottom). I have some `@examples` as well as some other parameters for each `@function`, `@mixin` etc. I even tried to completely remove the mixin etc examples, but the error persist, so I believe I am not yet at the point where `sass` is trying to compile my examples.

Here is an example of a mixin:
```

/// @name boxshadow
/// @group parameters
$boxshadows: (
         0: "rgba(0, 0, 0, 0.25) 0px 25px 50px -12px",
         1: "rgba(0, 0, 0, 0.06) 0px 2px 4px 0px inset"
);

/// @name box-shadow
/// @group utility
/// @param  {number}  $box-shadow-id - The ID of the box shadow from the $box-shadow-list
/// @return {list} - Returns a list of box shadow css properties to the mixin.
/// @example sass
/// .some-selector{
/// @include boxshadow(1);
/// }
@function box-shadow($box-shadow-id) {
    // SOME LOGIC
    @return 'Some CSS Property';
  } @else {
    @warn 'SOME WARNING`
    @return null;
  }
}
```

I have a `.sassdocrc` file, and played a lot but I am not sure if it works or not. I have tried pretty standard things, and tried to follow online examples, but everytime it seems that some path related issue occurs and I am not sure why and where. I get that its a YAML type of file, and I am quite sure my syntax is all right (if vs code is to be trusted), but I can't get any herman setting to work. Sassdoc settings work fine though.

```
# .sassdocrc (yaml)

herman:
    sass:
      includePaths:
        - './test-sin'
      use:
       - file: './scss/_sin.scss'
         namespace: 'example'
```

The folder i specify as `includePaths` is a folder i use for tests. Here is the folder structure.
```
test-sin/
     - scss/
             - _sin.scss
             - pages/
             - modules/
             - main-file-to-be-compiled-to-css.scss 
```

```
Unhandled rejection Template render error: (unknown path)
  Template render error: (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\templates\item\_item.njk)
  TypeError: Cannot read properties of undefined (reading 'toString')
    at Object._prettifyError (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:36:11)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:563:19
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:89:12)
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:131:12)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:571:11
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:36:12)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:613:9
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:330:3)
    at Template.getExported (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:611:10)
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:35:6)
    at createTemplate (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:315:9)
    at handle (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:327:11)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:339:9
    at next (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:328:7)
    at Object.asyncIter (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:334:3)
    at Environment.getTemplate (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:321:9)

Unhandled rejection Template render error: (unknown path)
  Template render error: (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\templates\item\_item.njk)
  TypeError: Cannot read properties of undefined (reading 'toString')
    at Object._prettifyError (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:36:11)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:563:19
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:89:12)
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:131:12)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:571:11
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:36:12)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:613:9
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:330:3)
    at Template.getExported (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:611:10)
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:35:6)
    at createTemplate (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:315:9)
    at handle (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:327:11)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:339:9
    at next (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:328:7)
    at Object.asyncIter (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:334:3)
    at Environment.getTemplate (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:321:9)

Unhandled rejection Template render error: (unknown path)
  Template render error: (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\templates\item\_item.njk)
  TypeError: Cannot read properties of undefined (reading 'toString')
    at Object._prettifyError (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:36:11)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:563:19
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:89:12)
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:131:12)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:571:11
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:36:12)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:613:9
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:330:3)
    at Template.getExported (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:611:10)
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:35:6)
    at createTemplate (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:315:9)
    at handle (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:327:11)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:339:9
    at next (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:328:7)
    at Object.asyncIter (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:334:3)
    at Environment.getTemplate (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:321:9)Unhandled rejection Template render error: (unknown path)
  Template render error: (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\templates\item\_item.njk)
  TypeError: Cannot read properties of undefined (reading 'toString')
    at Object._prettifyError (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:36:11)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:563:19
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:89:12)
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:131:12)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:571:11
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:36:12)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:613:9
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:330:3)
    at Template.getExported (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:611:10)
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:35:6)
    at createTemplate (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:315:9)
    at handle (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:327:11)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:339:9
    at next (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:328:7)
    at Object.asyncIter (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:334:3)
    at Environment.getTemplate (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:321:9)

Unhandled rejection Template render error: (unknown path)
  Template render error: (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\templates\item\_item.njk)
  TypeError: Cannot read properties of undefined (reading 'toString')
    at Object._prettifyError (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:36:11)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:563:19
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:89:12)
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:131:12)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:571:11
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:36:12)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:613:9
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:330:3)
    at Template.getExported (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:611:10)
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:35:6)
    at createTemplate (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:315:9)
    at handle (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:327:11)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:339:9
    at next (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:328:7)
    at Object.asyncIter (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:334:3)
    at Environment.getTemplate (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:321:9)

Unhandled rejection Template render error: (unknown path)
  Template render error: (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\templates\item\_item.njk)
  TypeError: Cannot read properties of undefined (reading 'toString')
    at Object._prettifyError (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:36:11)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:563:19
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:89:12)
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:131:12)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:571:11
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:36:12)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:613:9
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:330:3)
    at Template.getExported (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:611:10)
    at eval (eval at _compile (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:35:6)
    at createTemplate (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:315:9)
    at handle (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:327:11)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:339:9
    at next (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:328:7)
    at Object.asyncIter (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\lib.js:334:3)
    at Environment.getTemplate (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\sassdoc-theme-herman\node_modules\nunjucks\src\environment.js:321:9)
```

**Comment by jgerigmeyer** [comment] 2022-08-10 19:16
Hi @TheoKondak, sorry for the delayed response. Is this still not working for you? If so, would it be possible to point me to a repo where I can see the error for myself? Thanks!

**Comment by TheoKondak** [comment] 2022-08-17 20:03
Hi @jgerigmeyer , thanks for the reply! No problem for being late. Yes, I still have the issue. I managed to resolve some errors (2 out of 4) but there are still 2 remaining, and I am unable to locate the reason.

I have tried to remove every piece of documentation related code for each mixin/function etc but still I did not manage to find the source of the problem.

This is the repository: https://github.com/TheoKondak/Sinister/tree/main/scss

**Comment by jgerigmeyer** [comment] 2022-08-19 15:05
> Hi @jgerigmeyer , thanks for the reply! No problem for being late. Yes, I still have the issue. I managed to resolve some errors (2 out of 4) but there are still 2 remaining, and I am unable to locate the reason.

@TheoKondak I forked the repo, narrowed down to one file, and fixed the comments so that Herman renders the docs successfully. Hopefully that gets you started in the right direction!

https://github.com/TheoKondak/Sinister/pull/2

**Comment by TheoKondak** [comment] 2022-08-21 12:33
Thanks once again @jgerigmeyer ! With your help, and after a dozen hours of learning and troubleshooting I finally managed to get rid of the errors!

I managed to run sassdoc with the herman theme, which initially rendered only some of the  `.html` files.
- So I saw which `@group`s could not render an `.html` file properly. 
- Then renamed each `@group example` to `@group exampleTest01` etc to have a unique group for each function/mixin
- Run the `sassdoc \"sin-core\" --theme=herman` and check again which `@group`s cannot render an `.html` file.
- Then disabled the documentation lines for these files by replacing `///` with `//` to make them simple sass comments.

These are the files that have some kind of problem with the documentation. In my case are the following:

# Mixins and Functions with issues

Herman Doc has issues with the following files and their documentation

## Functions

- `_contains-func.scss`
- `_get-func.scss`
- `_getMap-func.scss`
- `_type-func.scss`
- `_flex-properties-beta.scss`

## Mixins

- `_help-func.scss`
- `_spacing.scss`


Now, I am not quite sure why these files have problems. It probably has to do with the way they work or something but as long as I add any documentation notation to these functions the errors start to appear.  Some of these functions just return `@debug` messages, but I don't think that that's problematic on it's own.

**Comment by jgerigmeyer** [comment] 2022-08-21 14:08
> Herman Doc has issues with the following files and their documentation

@TheoKondak It's difficult for me to see what's going on when I can't reproduce the issue. If you push a branch with the `test-sin` directory added, as well as a copy of the `sin.config` file, then I can take a look. Otherwise I'm not sure why those functions/mixins wouldn't work.

**Comment by TheoKondak** [comment] 2022-08-22 08:57
@jgerigmeyer I have created a new branch with the missing files and folders and you should be able to reproduce the issues now.

Here is the new branch: [theme-herman-troubleshooting](https://github.com/TheoKondak/Sinister/tree/theme-herman-troubleshooting

Tested scripts and they all work on this branch. 

To compile sass in the `test-sin` folder  you can use `npm run sass`  but first have to link the test sin by running `npm run link`.

**Comment by jgerigmeyer** [comment] 2022-08-22 15:09
> @jgerigmeyer I have created a new branch with the missing files and folders and you should be able to reproduce the issues now.

@TheoKondak I pulled that branch, re-enabled the SassDoc comments on the files you listed (e.g. `///` instead of `//`), and everything is still compiling fine. See https://github.com/TheoKondak/Sinister/pull/3

Is there something else I have to do to see the errors?

**Comment by TheoKondak** [comment] 2022-08-22 16:06
@jgerigmeyer I cloned [TheoKondak/Sinister#3](https://github.com/TheoKondak/Sinister/pull/3) and indeed it compiles fine for me too.

Then I went back to the main repo and tried to enable some of the comments ( `//` -> `///` ) for the problematic files myself, but the error occurred. Immediately.

Also, the `.sassdocrc` `sass.use` doesn't seem to work either.

I have tried uninstalling/reinstalling `sassdoc` and `sassdoc-theme-herman` but it did not change anything.

I am really perplexed about what might be wrong here. The environment is identical, but the behavior is different.

**Comment by jgerigmeyer** [comment] 2022-08-22 16:41
> I am really perplexed about what might be wrong here. The environment is identical, but the behavior is different.

@TheoKondak Yeah, I'm not sure either since I can't really test the `main` branch. There are a few other changes between those two branches too, so you might want to start with https://github.com/TheoKondak/Sinister/pull/3 and un-apply the changes one or two at a time to see when it stops working?

https://github.com/TheoKondak/Sinister/compare/main...jgerigmeyer:Sinister:theme-herman-troubleshooting

**Comment by jgerigmeyer** [comment] 2022-08-22 16:42
I'm happy to keep trying to help as I can, but I'm going to close this since (as of now) it doesn't seem to represent a bug in Herman.

**Closed by jgerigmeyer** 2022-08-22 16:42 UTC

**Comment by TheoKondak** [comment] 2022-08-23 10:10
@jgerigmeyer I merged with main, and Herman compiles successfully now. I guess I will never know the exact reason I was getting the errors, but since it works, I am fine with that 😄 

I cannot express my gratitude for your help. I don't want to consume more of your time, since it seems it was an issue on my end and not a Herman issue.

Thanks again!
